baseURL = 'https://techtree.id/'
languageCode = 'en-us'
title = 'Tech Tree'
theme = 'up-business-theme'

summaryLength = 20
timeout = '60'

[params]
title = "Tech Tree"
description = "We specialize in providing services to desing websites, applications, build and maintain business for customers."
images = [ "images/hero-image.png" ]
logo = "images/logo.png"
location = [
  "3891 Ranchview Dr. Richardson, California 62639"
]
contact = [ "hello@techtree.id", "207.555.0119" ]
copyright = "Â© 2023 Tech Tree All Rights Reserved"

  [params.favicons]
  themeColor = "#FFFFFF"
  backgroundColor = "#FFFFFF"
  faviconColor = "#000000"

  [params.social]
  dribbble = "#"
  instagram = "#"
  facebook = "#"
  twitter = "#"

[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "Our team"
url = "#our-teams"
weight = 2

[[menus.main]]
name = "Clients"
url = "#clients"
weight = 3

[[menus.main]]
name = "Portfolio"
url = "#portfolio"
weight = 4

# [[menus.main]]
# name = "Blog"
# url = "/blog"
# weight = 5

[[menus.buttons]]
name = "Contact Us"
url = "#footer"
weight = 5
pre = "btn btn-primary text-light"

[[menus.footer]]
name = "Home"
url = "#header"
weight = 1

[[menus.footer]]
name = "Our team"
url = "#our-teams"
weight = 2

[[menus.footer]]
name = "Clients"
url = "#clients"
weight = 3

[[menus.footer]]
name = "Portfolio"
url = "#portfolio"
weight = 4

# [[menus.footer]]
# name = "Blog"
# url = "/blog"
# weight = 5

[taxonomies]
series = "series"
tags = "tags"
